togglz.console.enabled: true
togglz:
    console:
      path: /togglzconsole
      secured: false
      use-management-port: false
      enabled: true
server.port: 8090
togglz.features.HEADER_TEXT.enabled: true
togglz.features.WELCOME_MESSAGE.enabled: false