togglz.console.enabled: true
togglz:
    feature-enums: com.vivekganesan.cddemo.featuretoggles.AppFeatures
    console:
      path: /togglz
      secured: false
      use-management-port: false
      enabled: true
server.port: 8090
togglz.features.HEADER_TEXT.enabled: true
togglz.features.WELCOME_MESSAGE.enabled: false